development:
  host: localhost
  port: 27017
  database: lagunitas_development

test:
  host: localhost 
  port: 27017
  database: lagunitas_test

staging:
  hosts: [[staging2.copious.com, 27017], [staging.copious.com, 27017], [staging3.copious.com, 27017]] 
  database: lagunitas_staging
  read_secondary: true
  max_retries_on_connection_failure: 3

demo:
  host: demo1.copious.com
  port: 27017
  database: lagunitas_demo

production:
  hosts: [[lag-mongo-1.copious.com, 27017], [lag-mongo-2.copious.com, 27017], [lag-mongo-3.copious.com, 27017]]
  database: lagunitas_production
  read_secondary: true
  max_retries_on_connection_failure: 3
  logger: false
