require 'lagunitas/models/collection_follow_notification'
require 'lagunitas/models/credit_granted_notification'
require 'lagunitas/models/feedback_decreased_notification'
require 'lagunitas/models/feedback_increased_notification'
require 'lagunitas/models/follow_notification'
require 'lagunitas/models/invite_sent_pileon_notification'
require 'lagunitas/models/listing_commented_notification'
require 'lagunitas/models/listing_like_notification'
require 'lagunitas/models/listing_flagged_notification'
require 'lagunitas/models/listing_save_notification'
require 'lagunitas/models/listing_suspended_notification'
require 'lagunitas/models/listing_replied_notification'
require 'lagunitas/models/listing_mentioned_notification'
require 'lagunitas/models/order_completed_notification'
require 'lagunitas/models/order_created_notification'
require 'lagunitas/models/order_delivered_notification'
require 'lagunitas/models/order_delivery_confirmation_period_elapsed_notification'
require 'lagunitas/models/order_failed_notification'
require 'lagunitas/models/order_shipped_notification'
require 'lagunitas/models/order_unrated_notification'
require 'lagunitas/models/order_unshipped_notification'
require 'lagunitas/models/seller_payment_paid_notification'
require 'lagunitas/models/seller_payment_rejected_notification'
require 'lagunitas/models/tracking_number_updated_notification'

require 'lagunitas/models/preferences'

require 'lagunitas/models/signup_credit_trigger'
require 'lagunitas/models/inviter_credit_trigger'
require 'lagunitas/models/invitee_credit_trigger'

require 'json/patch'
